import json
from typing import Literal


Locale = Literal["en", "zh-CN"]
DEFAULT_LOCALE: Locale = "en"
SUPPORTED_LOCALES: tuple[Locale, ...] = ("en", "zh-CN")
_STORAGE_KEY = "chemicalTrade.locale"

_MESSAGES: dict[Locale, dict[str, str]] = {
    "en": {
        "app.scope": "CHEMICAL TRADE COPILOT · APPROVED TDS/SDS EVIDENCE",
        "language.label": "Interface language",
        "language.english": "English",
        "language.chinese": "中文",
        "translation.machine": "Machine translated · Original analysis remains available",
        "translation.original": "Show original analysis text",
        "translation.failed": "The translated view is unavailable. The original analysis is shown without changing the review decision.",
        "entry.eyebrow": "Inquiry → Evidence → Reply",
        "entry.title": "First decide what can be answered. Then prepare the right reply.",
        "entry.description": "Paste a Chinese or English customer inquiry. The app separates technical, compliance, commercial, and logistics requests and recommends a product only when the approved documents support it.",
        "entry.inquiry": "Customer inquiry",
        "entry.target_market": "Target market",
        "entry.api_key_missing": "The DeepSeek API key has not been configured yet. The demo is available for interface review; inquiry analysis will be enabled after the key is added in Vercel.",
        "market.unknown": "Not specified",
        "market.EU": "European Union",
        "market.US": "United States",
        "market.GB": "United Kingdom",
        "market.CN": "China",
        "market.CA": "Canada",
        "market.AU": "Australia",
        "market.JP": "Japan",
        "market.KR": "South Korea",
        "market.other": "Other",
        "backup.open": "Open review backup",
        "backup.file": "Choose a review backup file",
        "backup.save": "Save review backup",
        "backup.invalid": "This review backup is invalid and was not opened.",
        "backup.changed": "The approved materials changed. Inquiry inputs were restored; analyze again.",
        "backup.restored": "Review backup restored.",
        "record.complete": "Confirm and complete review",
        "record.completed": "Completed review",
        "record.read_only": "This completed review is read-only.",
        "record.print": "Open print review",
        "record.decision": "Expert decision",
        "record.email_version": "Email version",
        "record.analysis_revision": "Analysis revision",
        "record.none": "None",
        "record.no_email": "No authorized customer email.",
        "record.status": "Review status",
        "record.in_progress": "In progress",
        "record.open_gaps": "Open gaps",
        "record.sources": "Controlled sources",
        "record.saved_at": "Saved at",
        "record.current_session": "Current session",
        "state.open": "Open",
        "state.closed": "Closed",
        "print.action": "Print / Save PDF",
        "print.live": "Live review",
        "print.internal_title": "Internal evidence review",
        "print.inquiry": "Inquiry",
        "print.conclusion": "Conclusion",
        "print.parameters": "Verified parameters",
        "print.parameter": "Parameter",
        "print.value": "Value",
        "print.conditions": "Conditions",
        "print.method": "Method",
        "print.no_parameters": "No verified parameters recorded.",
        "print.evidence": "Controlled evidence",
        "print.no_evidence": "No controlled citation is attached.",
        "print.gaps": "Review gaps",
        "print.no_gaps": "No review gaps recorded.",
        "print.decision": "Expert decision",
        "print.reviewer": "Technical reviewer",
        "print.date": "Date",
        "print.page": "Page {page}",
        "print.customer_email": "Customer email",
        "print.email_version": "Email version {version} · {language}{edited}",
        "page.inquiry": "Inquiry",
        "page.conclusion": "Conclusion",
        "page.gaps": "Gaps",
        "page.evidence": "Evidence",
        "page.decision": "Decision",
        "page.email": "Email",
        "page.print": "Print",
        "page.record": "Record",
        "page_title.inquiry": "Review inquiry",
        "page_title.conclusion": "Review conclusion",
        "page_title.gaps": "Review gaps",
        "page_title.evidence": "Review evidence",
        "page_title.decision": "Expert decision",
        "page_title.email": "Customer email",
        "page_title.print": "Print review",
        "page_title.record": "Review record",
        "entry.placeholder": "Example: Please confirm the MPDA-cured EPON Resin 8280 test conditions, and quote CFR Santos for 5 metric tons.",
        "entry.help": "Helpful details: final application, key performance requirement, destination country or port, quantity, delivery window, Incoterm, packaging, and certification needs. Missing details can be identified during analysis.",
        "entry.analyze": "Analyze inquiry",
        "entry.empty": "Enter a customer inquiry before starting the analysis.",
        "entry.spinner": "Validating technical documents and evidence guardrails...",
        "entry.failed": "The analysis could not be completed safely. Check the local API and index configuration, then try again. No unsupported result was shown.",
        "entry.footer": "Public demo · {scope} · No automatic email sending",
        "review.eyebrow": "Inquiry → Evidence → Expert decision",
        "review.title": "Technical review",
        "review.description": "Review the inquiry facts, document evidence, limitations, and open questions before authorizing any customer-facing draft.",
        "review.facts": "Inquiry facts",
        "review.no_facts": "No structured inquiry facts were extracted.",
        "review.ambiguities": "Ambiguities and possible interpretations",
        "review.hypothesis": "System hypothesis · Technical reviewer decision required",
        "review.candidates": "Internal candidates",
        "review.internal_candidate": "Internal candidate",
        "review.physical_page": "Physical page {page}",
        "review.conditions": "Applicable conditions: {value}",
        "review.evidence_limitation": "Evidence limitation:",
        "review.no_candidate": "No evidence-backed internal candidate is available for this inquiry.",
        "review.limits": "Evidence and decision limits",
        "review.followups": "Dynamic follow-up questions",
        "review.no_followups": "No follow-up question was generated for the current inquiry.",
        "review.decision": "Technical reviewer decision",
        "review.expert_decision": "Expert decision",
        "review.candidate": "Evidence-backed internal candidate",
        "review.candidate_placeholder": "Select one candidate",
        "review.apply": "Apply expert decision",
        "review.pending_info": "Pending technical review. No customer-facing draft is available.",
        "review.select_followup": "Select at least one current follow-up question to prepare a draft.",
        "review.do_not_recommend": "Do not recommend. Product recommendations and suitability language remain locked.",
        "decision.pending": "Pending — keep all external drafts locked",
        "decision.proceed": "Proceed with an evidence-backed candidate",
        "decision.needs_information": "Request selected customer information",
        "decision.do_not_recommend": "Do not recommend",
        "decision.exit.ask_customer": "Ask customer for information",
        "decision.exit.save_only": "Save record without replying",
        "decision.exit.technical_reply": "Authorize technical reply",
        "decision.gate.no_open_questions": "No open customer questions remain. Resolve by saving the record or authorizing an evidence-backed technical reply.",
        "decision.gate.no_evidence_candidate": "No evidence-backed technical reply is available. Ask an open customer question or save the record without replying.",
        "category.technical": "Technical",
        "category.compliance": "Compliance",
        "category.commercial": "Commercial",
        "category.logistics": "Logistics",
        "status.inquiry_explicit": "Inquiry explicit",
        "draft.language": "Email language",
        "draft.subject": "Email subject",
        "draft.optimize": "Optimize draft",
        "draft.generate_new_version": "Generate new version",
        "draft.optimize_prompt": "How should this email be improved?",
        "draft.version": "Draft version",
        "draft.edited": "Edited",
        "draft.copy": "Copy email",
        "draft.copied": "Copied",
        "draft.editor_missing": "Email editor not found",
        "draft.english": "English",
        "draft.chinese": "中文",
        "draft.english_reply": "Editable English reply",
        "draft.chinese_reply": "Editable Chinese reply",
        "draft.english_email": "Editable English email",
        "draft.chinese_email": "Editable Chinese email",
        "draft.caption": "Review and edit before copying. The app does not connect to an inbox or send messages.",
        "draft.followup_title": "Customer follow-up draft",
        "draft.followup_label": "Editable customer follow-up",
        "draft.followup_caption": "Only the questions selected by the technical reviewer are included. Review and edit before copying; the app does not send messages.",
        "action.new": "Start a new inquiry",
        "action.reanalyze": "Reanalyze inquiry",
        "result.validated": "Evidence validated",
        "result.supported_fallback": "Supported technical result",
        "result.supported_description": "A technical reply can be prepared from the approved evidence. Commercial, compliance, and logistics facts still require separate confirmation.",
        "result.open_items": "Open items: {value}",
        "result.next_action": "Next action: {value}",
        "result.why_title": "Why the technical conclusion holds",
        "result.why_description": "The approved technical source contains a test result for the specified cured system with its formulation, curing, and test conditions bound together.",
        "result.not_stated": "Not stated",
        "result.verified_fact": "Verified fact · specified cured system",
        "result.not_continuous": "Not a continuous-use temperature",
        "result.agent_ratio": "Curing agent and mix ratio",
        "result.cure_schedule": "Cure schedule",
        "result.verified_source": "Verified source",
        "result.fact_warning": "Document age, revision, and jurisdiction remain material limitations. A cured-system HDT result must not be presented as uncured-resin performance or continuous-use temperature.",
        "source.title": "Inspect the source page",
        "source.caption": "Click the authentic PDF page to open the viewer. Use Zoom in, Zoom out, Reset, or click the enlarged page to toggle between fit and 150%.",
        "source.error": "The approved source page could not be rendered: {error}",
        "source.physical_page": "Physical page {page}",
        "readiness.title": "What is still needed before a quotation",
        "readiness.customer": "Confirm with the customer",
        "readiness.internal": "Confirm internally",
        "readiness.stock": "Stock, MOQ, and available quantity",
        "readiness.price": "Price, currency, and quotation validity",
        "readiness.freight": "Freight and estimated shipping date",
        "readiness.payment": "Payment terms and packaging availability",
        "readiness.documents": "Document pack",
        "readiness.document_caption": "TDS: available · SDS: available, jurisdiction-specific · COA: not supplied and batch-specific · Destination-market documents: confirm when required",
        "decision_line.technical": "Technical",
        "decision_line.compliance": "Compliance",
        "decision_line.quotation": "Quotation",
        "decision_line.logistics": "Logistics",
    },
    "zh-CN": {
        "app.scope": "化工外贸技术审阅 · 已批准的 TDS/SDS 证据",
        "language.label": "界面语言",
        "language.english": "English",
        "language.chinese": "中文",
        "translation.machine": "机器翻译 · 可随时查看原始分析",
        "translation.original": "查看原始分析文本",
        "translation.failed": "翻译视图暂不可用。页面保留原始分析，专家决定没有改变。",
        "entry.eyebrow": "询盘 → 证据 → 回复",
        "entry.title": "先判断哪些问题能够回答，再准备正确的回复。",
        "entry.description": "粘贴中文或英文客户询盘。系统会区分技术、合规、商务和物流要求，并且只有在已批准资料能够支持时才允许推荐产品。",
        "entry.inquiry": "客户询盘",
        "entry.target_market": "目标市场",
        "entry.api_key_missing": "尚未配置 DeepSeek API Key。当前可以查看演示界面；在 Vercel 中添加密钥后即可启用询盘分析。",
        "market.unknown": "未指定",
        "market.EU": "欧盟",
        "market.US": "美国",
        "market.GB": "英国",
        "market.CN": "中国",
        "market.CA": "加拿大",
        "market.AU": "澳大利亚",
        "market.JP": "日本",
        "market.KR": "韩国",
        "market.other": "其他",
        "backup.open": "打开审阅备份",
        "backup.file": "选择审阅备份文件",
        "backup.save": "保存审阅备份",
        "backup.invalid": "该审阅备份无效，未打开。",
        "backup.changed": "已批准资料发生变化。仅恢复询盘输入，请重新分析。",
        "backup.restored": "审阅备份已恢复。",
        "record.complete": "确认并完成审阅",
        "record.completed": "审阅已完成",
        "record.read_only": "该审阅已完成，只能查看。",
        "record.print": "打开打印审阅",
        "record.decision": "专家决定",
        "record.email_version": "邮件版本",
        "record.analysis_revision": "分析修订",
        "record.none": "无",
        "record.no_email": "没有已授权的客户邮件。",
        "record.status": "审阅状态",
        "record.in_progress": "进行中",
        "record.open_gaps": "未关闭缺口",
        "record.sources": "受控来源",
        "record.saved_at": "保存时间",
        "record.current_session": "当前会话",
        "state.open": "未关闭",
        "state.closed": "已关闭",
        "print.action": "打印 / 保存 PDF",
        "print.live": "实时审阅",
        "print.internal_title": "内部证据审阅",
        "print.inquiry": "询盘",
        "print.conclusion": "结论",
        "print.parameters": "已核验参数",
        "print.parameter": "参数",
        "print.value": "数值",
        "print.conditions": "适用条件",
        "print.method": "测试方法",
        "print.no_parameters": "未记录已核验参数。",
        "print.evidence": "受控证据",
        "print.no_evidence": "未关联受控引用。",
        "print.gaps": "审阅缺口",
        "print.no_gaps": "未记录审阅缺口。",
        "print.decision": "专家决定",
        "print.reviewer": "技术审阅人",
        "print.date": "日期",
        "print.page": "第 {page} 页",
        "print.customer_email": "客户邮件",
        "print.email_version": "邮件版本 {version} · {language}{edited}",
        "page.inquiry": "询盘",
        "page.conclusion": "结论",
        "page.gaps": "缺口",
        "page.evidence": "证据",
        "page.decision": "决定",
        "page.email": "邮件",
        "page.print": "打印",
        "page.record": "记录",
        "page_title.inquiry": "审阅询盘",
        "page_title.conclusion": "审阅结论",
        "page_title.gaps": "审阅缺口",
        "page_title.evidence": "审阅证据",
        "page_title.decision": "专家决定",
        "page_title.email": "客户邮件",
        "page_title.print": "打印审阅",
        "page_title.record": "审阅记录",
        "entry.placeholder": "示例：请确认使用 MPDA 固化的 EPON Resin 8280 测试条件，并按 5 吨报价 CFR Santos。",
        "entry.help": "建议提供：最终用途、关键性能、目的国家或港口、数量、交付窗口、贸易术语、包装和认证要求。系统会识别缺失信息。",
        "entry.analyze": "分析询盘",
        "entry.empty": "请先输入客户询盘。",
        "entry.spinner": "正在核验技术资料和证据门禁……",
        "entry.failed": "无法安全完成分析。请检查本地 API 和索引配置后重试；系统没有显示未经支持的结果。",
        "entry.footer": "公开演示 · {scope} · 不自动发送邮件",
        "review.eyebrow": "询盘 → 证据 → 专家决定",
        "review.title": "技术审阅",
        "review.description": "授权任何对外草稿前，请审阅询盘事实、资料证据、限制和待确认问题。",
        "review.facts": "询盘事实",
        "review.no_facts": "没有提取到结构化询盘事实。",
        "review.ambiguities": "歧义与可能解释",
        "review.hypothesis": "系统推测 · 需要技术人员判断",
        "review.candidates": "内部候选",
        "review.internal_candidate": "内部候选",
        "review.physical_page": "物理页 {page}",
        "review.conditions": "适用条件：{value}",
        "review.evidence_limitation": "证据限制：",
        "review.no_candidate": "当前询盘没有具备证据支持的内部候选。",
        "review.limits": "证据与判断边界",
        "review.followups": "动态追问",
        "review.no_followups": "当前询盘没有生成追问。",
        "review.decision": "技术人员决定",
        "review.expert_decision": "专家决定",
        "review.candidate": "有证据的内部候选",
        "review.candidate_placeholder": "选择一个候选",
        "review.apply": "应用专家决定",
        "review.pending_info": "等待技术审阅，当前没有可对外使用的草稿。",
        "review.select_followup": "请至少选择一个当前追问后再准备草稿。",
        "review.do_not_recommend": "不建议推荐。产品推荐和暗示适用性的内容仍被锁定。",
        "decision.pending": "待判断——锁定全部对外草稿",
        "decision.proceed": "选择有证据的候选并继续",
        "decision.needs_information": "请求客户补充已选信息",
        "decision.do_not_recommend": "不建议推荐",
        "decision.exit.ask_customer": "向客户追问信息",
        "decision.exit.save_only": "仅保存记录，不回复",
        "decision.exit.technical_reply": "授权技术回复",
        "decision.gate.no_open_questions": "当前没有未解决的客户问题。请选择仅保存记录，或授权有证据支持的技术回复。",
        "decision.gate.no_evidence_candidate": "当前没有有证据支持的技术回复。请选择开放的客户问题进行追问，或仅保存记录。",
        "category.technical": "技术",
        "category.compliance": "合规",
        "category.commercial": "商务",
        "category.logistics": "物流",
        "status.inquiry_explicit": "询盘明确",
        "draft.language": "邮件语言",
        "draft.subject": "邮件主题",
        "draft.optimize": "优化草稿",
        "draft.generate_new_version": "生成新版本",
        "draft.optimize_prompt": "如何优化这封邮件？",
        "draft.version": "草稿版本",
        "draft.edited": "已编辑",
        "draft.copy": "复制邮件",
        "draft.copied": "已复制",
        "draft.editor_missing": "未找到邮件编辑框",
        "draft.english": "English",
        "draft.chinese": "中文",
        "draft.english_reply": "可编辑英文回复",
        "draft.chinese_reply": "可编辑中文回复",
        "draft.english_email": "可编辑英文邮件",
        "draft.chinese_email": "可编辑中文邮件",
        "draft.caption": "复制前请检查和编辑。应用不会连接邮箱或自动发送邮件。",
        "draft.followup_title": "客户追问草稿",
        "draft.followup_label": "可编辑客户追问",
        "draft.followup_caption": "仅包含技术人员勾选的问题。复制前请检查和编辑；应用不会自动发送。",
        "action.new": "开始新询盘",
        "action.reanalyze": "重新分析询盘",
        "result.validated": "证据已核验",
        "result.supported_fallback": "有证据支持的技术结论",
        "result.supported_description": "可依据已批准证据准备技术回复；商务、合规和物流事实仍须分别确认。",
        "result.open_items": "待确认事项：{value}",
        "result.next_action": "下一步：{value}",
        "result.why_title": "技术结论依据",
        "result.why_description": "已批准技术资料记录了指定固化体系的测试结果，并同时绑定了配方、固化和测试条件。",
        "result.not_stated": "未说明",
        "result.verified_fact": "已核验事实 · 指定固化体系",
        "result.not_continuous": "不等于连续使用温度",
        "result.agent_ratio": "固化剂与配比",
        "result.cure_schedule": "固化制度",
        "result.verified_source": "已核验来源",
        "result.fact_warning": "文件年份、版本和适用地区仍是重要限制。固化体系的 HDT 结果不得表述为未固化树脂性能或连续使用温度。",
        "source.title": "查看原始证据页",
        "source.caption": "点击真实 PDF 页面打开查看器；可放大、缩小、重置，或点击大图在适应宽度与 150% 之间切换。",
        "source.error": "无法呈现已批准的原始证据页：{error}",
        "source.physical_page": "物理页 {page}",
        "readiness.title": "报价前仍需确认",
        "readiness.customer": "向客户确认",
        "readiness.internal": "内部确认",
        "readiness.stock": "库存、MOQ 和可供应数量",
        "readiness.price": "价格、币种和报价有效期",
        "readiness.freight": "运费和预计装运日期",
        "readiness.payment": "付款条件和包装可用性",
        "readiness.documents": "资料包",
        "readiness.document_caption": "TDS：已有 · SDS：已有但与地区相关 · COA：尚未提供且与批次相关 · 目的市场资料：需要时确认",
        "decision_line.technical": "技术",
        "decision_line.compliance": "合规",
        "decision_line.quotation": "报价",
        "decision_line.logistics": "物流",
    },
}

if set(_MESSAGES["en"]) != set(_MESSAGES["zh-CN"]):
    raise RuntimeError("English and Chinese localization keys must match")

_VIEW_MESSAGE_KEYS = {
    "Not requested": "view.not_requested",
    "More evidence required": "view.more_evidence",
    "Confirmation required": "view.confirmation",
    "Ready to reply": "view.ready",
    "Evidence available": "view.evidence_available",
    "Inputs required": "view.inputs_required",
    "Do not quote yet": "view.do_not_quote",
    "Technical reply ready; quotation inputs required": "view.headline_quote_inputs",
    "Technical reply ready": "view.headline_ready",
    "More evidence is required before recommending a product": "view.headline_more_evidence",
    "Technical scope or operating conditions": "view.open_technical",
    "Target-market regulatory requirements": "view.open_compliance",
    "Commercial terms and availability": "view.open_commercial",
    "Destination and shipping terms": "view.open_logistics",
    "Prepare the evidence-grounded technical reply": "view.next_reply",
    "Collect the missing technical conditions": "view.next_technical",
    "Collect customer and internal quotation inputs": "view.next_quotation",
    "Obtain additional approved product evidence": "view.next_evidence",
    "What is the final application?": "view.question_application",
    "Is the operating condition continuous, intermittent, or a short peak?": "view.question_duration",
    "What exposure medium, duration, and failure criterion apply?": "view.question_exposure",
    "Which target country, regulation, certification, or customer standard applies?": "view.question_compliance",
    "What quantity, delivery window, and packaging are required?": "view.question_commercial",
    "What destination port and named Incoterm place should be used?": "view.question_logistics",
}

_VIEW_MESSAGES: dict[Locale, dict[str, str]] = {
    "en": {key: value for value, key in _VIEW_MESSAGE_KEYS.items()},
    "zh-CN": {
        "view.not_requested": "未提出",
        "view.more_evidence": "需要更多证据",
        "view.confirmation": "需要确认",
        "view.ready": "可准备回复",
        "view.evidence_available": "已有证据",
        "view.inputs_required": "需要补充信息",
        "view.do_not_quote": "暂不能报价",
        "view.headline_quote_inputs": "技术回复已具备条件；报价信息仍需补充",
        "view.headline_ready": "技术回复已具备条件",
        "view.headline_more_evidence": "推荐产品前仍需更多证据",
        "view.open_technical": "技术范围或使用条件",
        "view.open_compliance": "目标市场合规要求",
        "view.open_commercial": "商务条款与供应情况",
        "view.open_logistics": "目的地与运输条款",
        "view.next_reply": "准备基于证据的技术回复",
        "view.next_technical": "收集缺失的技术条件",
        "view.next_quotation": "收集客户与内部报价信息",
        "view.next_evidence": "取得更多已批准产品证据",
        "view.question_application": "最终用途是什么？",
        "view.question_duration": "该使用条件是连续、间歇还是短时峰值？",
        "view.question_exposure": "接触介质、持续时间和失效判据分别是什么？",
        "view.question_compliance": "适用哪个目标国家、法规、认证或客户标准？",
        "view.question_commercial": "所需数量、交付窗口和包装是什么？",
        "view.question_logistics": "应使用哪个目的港和 Incoterm 指定地点？",
    },
}

if set(_VIEW_MESSAGES["en"]) != set(_VIEW_MESSAGES["zh-CN"]):
    raise RuntimeError("English and Chinese view-message keys must match")


def normalize_locale(value: object) -> Locale:
    return value if value in SUPPORTED_LOCALES else DEFAULT_LOCALE  # type: ignore[return-value]


def text(key: str, locale: Locale, **values: object) -> str:
    return _MESSAGES[locale][key].format(**values)


def view_text(value: str, locale: Locale) -> str:
    key = _VIEW_MESSAGE_KEYS.get(value)
    return _VIEW_MESSAGES[locale].get(key, value) if key else value


def browser_locale_script(locale: Locale) -> str:
    allowed = json.dumps(list(SUPPORTED_LOCALES), ensure_ascii=False)
    current = json.dumps(locale)
    key = json.dumps(_STORAGE_KEY)
    return f"""<script>
(() => {{
  const allowed = {allowed};
  const storageKey = {key};
  const current = {current};
  const params = new URLSearchParams(window.location.search);
  const fromUrl = params.get('lang');
  try {{
    if (allowed.includes(fromUrl)) {{
      window.localStorage.setItem(storageKey, fromUrl);
      return;
    }}
    const saved = window.localStorage.getItem(storageKey);
    if (allowed.includes(saved) && saved !== current) {{
      params.set('lang', saved);
      window.location.replace(window.location.pathname + '?' + params.toString());
    }} else {{
      window.localStorage.setItem(storageKey, current);
    }}
  }} catch (_) {{
    // Browser storage can be disabled. The server-side English fallback remains valid.
  }}
}})();
</script>"""
